//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeReservas_PF.ServiceFullDay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFullDay.IServiceSoap_FullDay")]
    public interface IServiceSoap_FullDay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayResponse")]
        ReservaEntidades.Estructura_Promocion_FullDay_Lista obtenerPromocionFullDay(int pk_origen, int pk_destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayResponse")]
        System.Threading.Tasks.Task<ReservaEntidades.Estructura_Promocion_FullDay_Lista> obtenerPromocionFullDayAsync(int pk_origen, int pk_destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayPorId", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayPorIdResponse")]
        ReservaEntidades.Estructura_Promocion_FullDay obtenerPromocionFullDayPorId(int Pk_promocionFullDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayPorId", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayPorIdResponse")]
        System.Threading.Tasks.Task<ReservaEntidades.Estructura_Promocion_FullDay> obtenerPromocionFullDayPorIdAsync(int Pk_promocionFullDay);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSoap_FullDayChannel : SistemaDeReservas_PF.ServiceFullDay.IServiceSoap_FullDay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoap_FullDayClient : System.ServiceModel.ClientBase<SistemaDeReservas_PF.ServiceFullDay.IServiceSoap_FullDay>, SistemaDeReservas_PF.ServiceFullDay.IServiceSoap_FullDay {
        
        public ServiceSoap_FullDayClient() {
        }
        
        public ServiceSoap_FullDayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoap_FullDayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoap_FullDayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoap_FullDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReservaEntidades.Estructura_Promocion_FullDay_Lista obtenerPromocionFullDay(int pk_origen, int pk_destino, System.DateTime fecha) {
            return base.Channel.obtenerPromocionFullDay(pk_origen, pk_destino, fecha);
        }
        
        public System.Threading.Tasks.Task<ReservaEntidades.Estructura_Promocion_FullDay_Lista> obtenerPromocionFullDayAsync(int pk_origen, int pk_destino, System.DateTime fecha) {
            return base.Channel.obtenerPromocionFullDayAsync(pk_origen, pk_destino, fecha);
        }
        
        public ReservaEntidades.Estructura_Promocion_FullDay obtenerPromocionFullDayPorId(int Pk_promocionFullDay) {
            return base.Channel.obtenerPromocionFullDayPorId(Pk_promocionFullDay);
        }
        
        public System.Threading.Tasks.Task<ReservaEntidades.Estructura_Promocion_FullDay> obtenerPromocionFullDayPorIdAsync(int Pk_promocionFullDay) {
            return base.Channel.obtenerPromocionFullDayPorIdAsync(Pk_promocionFullDay);
        }
    }
}
