//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioProyecto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estructura_Promocion_FullDay_Lista", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Estructura_Promocion_FullDay_Lista : object
    {
        
        private string codigoField;
        
        private ServicioProyecto.Promocion_FullDay[] dataField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioProyecto.Promocion_FullDay[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promocion_FullDay", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Promocion_FullDay : object
    {
        
        private int CuposField;
        
        private string DescripcionField;
        
        private int Pk_promocionFullDayField;
        
        private double PrecioField;
        
        private string fecha_validaField;
        
        private string rutaField;
        
        private string rutaImagenField;
        
        private string tipoPromocionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cupos
        {
            get
            {
                return this.CuposField;
            }
            set
            {
                this.CuposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pk_promocionFullDay
        {
            get
            {
                return this.Pk_promocionFullDayField;
            }
            set
            {
                this.Pk_promocionFullDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha_valida
        {
            get
            {
                return this.fecha_validaField;
            }
            set
            {
                this.fecha_validaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruta
        {
            get
            {
                return this.rutaField;
            }
            set
            {
                this.rutaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutaImagen
        {
            get
            {
                return this.rutaImagenField;
            }
            set
            {
                this.rutaImagenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoPromocion
        {
            get
            {
                return this.tipoPromocionField;
            }
            set
            {
                this.tipoPromocionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estructura_Promocion_FullDay", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Estructura_Promocion_FullDay : object
    {
        
        private string codigoField;
        
        private ServicioProyecto.Promocion_FullDay dataField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioProyecto.Promocion_FullDay data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaFullDay", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class ReservaFullDay : object
    {
        
        private string ApellidoField;
        
        private string Dni_clienteField;
        
        private string EstadoField;
        
        private System.DateTime Fecha_GeneradoField;
        
        private System.DateTime Fecha_ViajeField;
        
        private int Fk_DestinoField;
        
        private int Fk_OrigenField;
        
        private string NombreField;
        
        private int Pk_Reserva_FullDayField;
        
        private string TelefonoField;
        
        private int cantidadField;
        
        private string correoField;
        
        private double precioTotalField;
        
        private double precioUnitarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_cliente
        {
            get
            {
                return this.Dni_clienteField;
            }
            set
            {
                this.Dni_clienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Generado
        {
            get
            {
                return this.Fecha_GeneradoField;
            }
            set
            {
                this.Fecha_GeneradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Viaje
        {
            get
            {
                return this.Fecha_ViajeField;
            }
            set
            {
                this.Fecha_ViajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fk_Destino
        {
            get
            {
                return this.Fk_DestinoField;
            }
            set
            {
                this.Fk_DestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fk_Origen
        {
            get
            {
                return this.Fk_OrigenField;
            }
            set
            {
                this.Fk_OrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pk_Reserva_FullDay
        {
            get
            {
                return this.Pk_Reserva_FullDayField;
            }
            set
            {
                this.Pk_Reserva_FullDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precioTotal
        {
            get
            {
                return this.precioTotalField;
            }
            set
            {
                this.precioTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precioUnitario
        {
            get
            {
                return this.precioUnitarioField;
            }
            set
            {
                this.precioUnitarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estructura_Post_int", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Estructura_Post_int : object
    {
        
        private string codigoField;
        
        private int dataField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estructura_Post_Bool", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Estructura_Post_Bool : object
    {
        
        private string codigoField;
        
        private bool dataField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estructura_ReservaFullDay", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Estructura_ReservaFullDay : object
    {
        
        private string codigoField;
        
        private ServicioProyecto.ReservaFullDay dataField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioProyecto.ReservaFullDay data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estructura_ReservaFullDay_Lista", Namespace="http://schemas.datacontract.org/2004/07/ReservaEntidades")]
    public partial class Estructura_ReservaFullDay_Lista : object
    {
        
        private string codigoField;
        
        private ServicioProyecto.ReservaFullDay[] dataField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioProyecto.ReservaFullDay[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioProyecto.IServiceSoap_FullDay")]
    public interface IServiceSoap_FullDay
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_Promocion_FullDay_Lista> obtenerPromocionFullDayAsync(int pk_origen, int pk_destino, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayPorId", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/obtenerPromocionFullDayPorIdResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_Promocion_FullDay> obtenerPromocionFullDayPorIdAsync(int Pk_promocionFullDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/RegistrarReservaFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/RegistrarReservaFullDayResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_Post_int> RegistrarReservaFullDayAsync(ServicioProyecto.ReservaFullDay reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/ModificarReservaFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/ModificarReservaFullDayResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_Post_Bool> ModificarReservaFullDayAsync(ServicioProyecto.ReservaFullDay reserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/ObtenerReservaFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/ObtenerReservaFullDayResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_ReservaFullDay> ObtenerReservaFullDayAsync(int Pk_Reserva_FullDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/EliminarReservaFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/EliminarReservaFullDayResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_Post_Bool> EliminarReservaFullDayAsync(int Pk_Reserva_FullDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap_FullDay/ObtenerReservasFullDay", ReplyAction="http://tempuri.org/IServiceSoap_FullDay/ObtenerReservasFullDayResponse")]
        System.Threading.Tasks.Task<ServicioProyecto.Estructura_ReservaFullDay_Lista> ObtenerReservasFullDayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceSoap_FullDayChannel : ServicioProyecto.IServiceSoap_FullDay, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoap_FullDayClient : System.ServiceModel.ClientBase<ServicioProyecto.IServiceSoap_FullDay>, ServicioProyecto.IServiceSoap_FullDay
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoap_FullDayClient() : 
                base(ServiceSoap_FullDayClient.GetDefaultBinding(), ServiceSoap_FullDayClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceSoap_FullDay.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoap_FullDayClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoap_FullDayClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoap_FullDayClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoap_FullDayClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoap_FullDayClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoap_FullDayClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoap_FullDayClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoap_FullDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_Promocion_FullDay_Lista> obtenerPromocionFullDayAsync(int pk_origen, int pk_destino, System.DateTime fecha)
        {
            return base.Channel.obtenerPromocionFullDayAsync(pk_origen, pk_destino, fecha);
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_Promocion_FullDay> obtenerPromocionFullDayPorIdAsync(int Pk_promocionFullDay)
        {
            return base.Channel.obtenerPromocionFullDayPorIdAsync(Pk_promocionFullDay);
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_Post_int> RegistrarReservaFullDayAsync(ServicioProyecto.ReservaFullDay reserva)
        {
            return base.Channel.RegistrarReservaFullDayAsync(reserva);
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_Post_Bool> ModificarReservaFullDayAsync(ServicioProyecto.ReservaFullDay reserva)
        {
            return base.Channel.ModificarReservaFullDayAsync(reserva);
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_ReservaFullDay> ObtenerReservaFullDayAsync(int Pk_Reserva_FullDay)
        {
            return base.Channel.ObtenerReservaFullDayAsync(Pk_Reserva_FullDay);
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_Post_Bool> EliminarReservaFullDayAsync(int Pk_Reserva_FullDay)
        {
            return base.Channel.EliminarReservaFullDayAsync(Pk_Reserva_FullDay);
        }
        
        public System.Threading.Tasks.Task<ServicioProyecto.Estructura_ReservaFullDay_Lista> ObtenerReservasFullDayAsync()
        {
            return base.Channel.ObtenerReservasFullDayAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceSoap_FullDay))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceSoap_FullDay))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60705/ServiceSoap_FullDay.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceSoap_FullDayClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceSoap_FullDay);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceSoap_FullDayClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceSoap_FullDay);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceSoap_FullDay,
        }
    }
}
